### ISSUE TITLE
Error RuntimeError: new_Decoder returned -1

### ISSUE THREAD

**Issue by sabas1080** [fcooper/beagleman#2]
Hi

I have the next error

```
Traceback (most recent call last):
  File "beagleman.py", line 80, in <module>
    decoder = Decoder(config)
  File "/usr/local/lib/python2.7/dist-packages/pocketsphinx/pocketsphinx.py", line 266, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1
```

Thanks

**Comment by sabas1080** [comment]
solved

 Start User configuration settings for Raspberry Pi
